### ISSUE TITLE
Response is altered after upgrade

### ISSUE THREAD

**Issue by phun-ky** [wheresrhys/fetch-mock#265]
Possibly related to #236 

These test:

    it('should not parse JSON if content-type is not set', done => {
      const expectedResponse = {
        status: 200,
        statusText: 'OK',
        body: { a: 1 }
      };
      fetchMock.mock('*', expectedResponse);
      fetch('http://<domain>').then(response => {
        expect(response.body).to.not.be.deep.equal(expectedResponse);
        parseResponse(response)
          .then(data => {
            expect(data).to.be.deep.equal(JSON.stringify(expectedResponse.body));
            done();
          })
          .catch(done);
      });
    });
    it('should parse JSON if application/json is set', done => {
      const expectedResponse = {
        status: 200,
        statusText: 'OK',
        headers: {
          'Content-Type': 'application/json'
        },
        body: { a: 1 }
      };
      fetchMock.mock('*', expectedResponse);
      fetch('http://<domain>').then(response => {
        expect(response.body).to.not.be.deep.equal(expectedResponse);
        parseResponse(response)
          .then(data => {
            expect(data).to.be.deep.equal(expectedResponse.body);
            done();
          })
          .catch(done);
      });
    });

Worked before upgrading to latest, now, the `expectedResponse` is altered:

    1) parseResponse
         should not parse JSON if content-type is not set:
       AssertionError: expected { Object (status, statusText, ...) } to deeply equal '{"a":1}'
        at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:1020:19)
        at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
        at src/client/lib/__tests__/parseResponse.spec.js:20:35
        at <anonymous>

    2) parseResponse
         should parse JSON if application/json is set:

        AssertionError: expected { Object (status, statusText, ...) } to deeply equal { a: 1 }
        + expected - actual

         {
        -  "body": {
        -    "a": 1
        -  }
        -  "headers": {
        -    "Content-Type": "application/json"
        -  }
        -  "status": 200
        -  "statusText": "OK"
        +  "a": 1
         }

        at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:1020:19)
        at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
        at src/client/lib/__tests__/parseResponse.spec.js:40:35
        at <anonymous>

parseResponse.js:

    const parseResponse = response => {
      const contentType = response.headers.get('content-type');
      return response.text().then(text => {
        if (contentType && contentType.includes('application/json') && text) {
          return JSON.parse(text);
        }
        return text;
      });
    };

**Comment by phun-ky** [comment]
Ok, updated my `expectedResponse`'s to match the documentation (hard to find that out :S ), but now my last test will not go through:

    /*eslint-env node, mocha */
    import fetchMock from 'fetch-mock/es5/server';
    import { expect } from 'chai';

    import parseResponse from 'lib/parseResponse';

    describe('parseResponse', () => {
      afterEach(() => {
        fetchMock.reset();
        fetchMock.restore();
      });
      it('should not parse JSON if content-type is not set', done => {
        const expectedResponse = {
          status: 200,
          body: '{ a: 1 }'
        };
        fetchMock.mock('*', expectedResponse);
        fetch('<path>').then(response => {
          expect(response.body).to.not.be.deep.equal(expectedResponse);
          parseResponse(response)
            .then(data => {
              expect(data).to.be.equal('{ a: 1 }');
              done();
            })
            .catch(done);
        });
      });
      it('should parse JSON if application/json is set', done => {
        const expectedResponse = {
          status: 200,
          headers: new Headers({ 'Content-Type': 'application/json' }),
          body: { a: 1 }
        };
        fetchMock.mock('*', expectedResponse);
        fetch('<path>').then(response => {
          expect(response.body).to.not.be.deep.equal(expectedResponse);
          parseResponse(response)
            .then(data => {
              expect(data).to.be.deep.equal(expectedResponse.body);
              done();
            })
            .catch(done);
        });
      });

      it('should not parse JSON if application/xml is set', done => {
        const expectedResponse = {
          status: 200,
          headers: new Headers({ 'Content-Type': 'application/xml' }),
          body: 'BODY'
        };
        fetchMock.mock('*', expectedResponse);
        fetch('http://if.no').then(response => {
          expect(response.body).to.not.be.equal(expectedResponse.body);
          parseResponse(response)
            .then(data => {
              expect(data).to.be.equal(expectedResponse.body);
              done();
            })
            .catch(done);
        });
      });
    });


    (node:8183) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError: expected 'BODY' to not equal 'BODY'
    (node:8183) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

      5 passing (5s)
      1 failing

      1) parseResponse
           should not parse JSON if application/xml is set:
         Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
