### ISSUE TITLE
sendAsJson should default to false if response status is 202

### ISSUE THREAD

**Issue by jgerigmeyer** [wheresrhys/fetch-mock#384]
If a response status is set to a code that returns no data (e.g. `202`), the default setting of `sendAsJson: true` sets the content header and triggers an error in node-fetch:

```js
fetchMock.postOnce('/my/url/', 202);
fetch('/my/url/', { method: 'POST' });
```

```
    TypeError: Cannot read property 'on' of undefined

    > 10 | const getResponse = resp => resp.text()
         |                                  ^

      at node_modules/node-fetch/lib/body.js:122:13
      at Response.Object.<anonymous>.Body._decode (node_modules/node-fetch/lib/body.js:96:9)
      at Response.Object.<anonymous>.Body.text (node_modules/node-fetch/lib/body.js:61:14)
      at Object.apply (node_modules/fetch-mock/src/lib/response-builder.js:152:28)
```

With `sendAsJson: false`, this works as expected:

```js
fetchMock.postOnce('/my/url/', { status: 202, sendAsJson: false });
fetch('/my/url/', { method: 'POST' });
```

I'm not sure this is exactly a bug, but it's counter-intuitive to need to set `sendAsJson` for empty data responses, and took me awhile to debug. Forgive me if I'm missing something obvious!

**Comment by wheresrhys** [comment]
This sounds like a bug as sendAsJson's effects are only supposed to kick in if the response you provided was an object, so it's odd it happens when you just pass a status.

I'll investigate as soon as I can - might have time this weekend

**Comment by wheresrhys** [comment]
I can't reproduce this bug. Can you either:
- clone this repo and submit a PR with a failing test 
- create a repo where the problem occurs that I can clone and use to investigate

Also, if you're not already on v7, please try upgrading to it to see if it fixes your problem

Thanks

**Comment by wheresrhys** [comment]
closing due to inactivity
