### ISSUE TITLE
Error when installing with NPM: typeerror Error: Missing required argument #1

### ISSUE THREAD

**Issue by danielBingham** [wheresrhys/fetch-mock#507]
Attempted to install `fetch-mock` and got the following error:
```
$ npm install fetch-mock --save-dev
npm ERR! Linux 5.3.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "fetch-mock" "--save-dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:190:5
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (/usr/share/npm/lib/install/deps.js:188:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

This is on Ubuntu 18.04.1.  I'm not having issues installing any other packages, however, I'm getting this consistently with `fetch-mock`. I've tried installing older versions, and I get the same issue. 

Contents of npm-debug:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'fetch-mock',
1 verbose cli   '--save-dev' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData fetch-mock
8 silly fetchNamedPackageData fetch-mock
9 silly mapToRegistry name fetch-mock
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/fetch-mock
13 verbose request uri https://registry.npmjs.org/fetch-mock
14 verbose request no auth needed
15 info attempt registry request try #1 at 4:59:56 PM
16 verbose request id 4f693c16a33a67d9
17 verbose etag W/"2d84d419314fa8a0bb93279e423e8bdd"
18 verbose lastModified Tue, 18 Feb 2020 13:38:25 GMT
19 http request GET https://registry.npmjs.org/fetch-mock
20 http 304 https://registry.npmjs.org/fetch-mock
21 verbose headers { date: 'Thu, 20 Feb 2020 21:59:56 GMT',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'set-cookie':
21 verbose headers    [ '__cfduid=dc7d6fdf06a656ca2718ea7e612ab3f451582235996; expires=Sat, 21-Mar-20 21:59:56 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
21 verbose headers   'cf-ray': '5683c0227ac2f21a-ORD',
21 verbose headers   age: '2909',
21 verbose headers   'cache-control': 'public, max-age=300',
21 verbose headers   etag: '"2d84d419314fa8a0bb93279e423e8bdd"',
21 verbose headers   'last-modified': 'Tue, 18 Feb 2020 13:38:25 GMT',
21 verbose headers   vary: 'Accept-Encoding',
21 verbose headers   'cf-cache-status': 'HIT',
21 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
21 verbose headers   server: 'cloudflare' }
22 silly get cb [ 304,
22 silly get   { date: 'Thu, 20 Feb 2020 21:59:56 GMT',
22 silly get     connection: 'keep-alive',
22 silly get     'set-cookie':
22 silly get      [ '__cfduid=dc7d6fdf06a656ca2718ea7e612ab3f451582235996; expires=Sat, 21-Mar-20 21:59:56 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
22 silly get     'cf-ray': '5683c0227ac2f21a-ORD',
22 silly get     age: '2909',
22 silly get     'cache-control': 'public, max-age=300',
22 silly get     etag: '"2d84d419314fa8a0bb93279e423e8bdd"',
22 silly get     'last-modified': 'Tue, 18 Feb 2020 13:38:25 GMT',
22 silly get     vary: 'Accept-Encoding',
22 silly get     'cf-cache-status': 'HIT',
22 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
22 silly get     server: 'cloudflare' } ]
23 verbose etag https://registry.npmjs.org/fetch-mock from cache
24 verbose get saving fetch-mock to /home/dbingham/.npm/registry.npmjs.org/fetch-mock/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 verbose stack Error: Missing required argument #1
37 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
37 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
37 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
37 verbose stack     at /usr/share/npm/lib/install/deps.js:190:5
37 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
37 verbose stack     at Array.forEach (<anonymous>)
37 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
37 verbose stack     at Array.forEach (<anonymous>)
37 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
37 verbose stack     at exports.loadRequestedDeps (/usr/share/npm/lib/install/deps.js:188:3)
38 verbose cwd /home/dbingham/src/peerreview
39 error Linux 5.3.0-28-generic
40 error argv "/usr/bin/node" "/usr/bin/npm" "install" "fetch-mock" "--save-dev"
41 error node v8.10.0
42 error npm  v3.5.2
43 error code EMISSINGARG
44 error typeerror Error: Missing required argument #1
44 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
44 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
44 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
44 error typeerror     at /usr/share/npm/lib/install/deps.js:190:5
44 error typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
44 error typeerror     at Array.forEach (<anonymous>)
44 error typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
44 error typeerror     at Array.forEach (<anonymous>)
44 error typeerror     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
44 error typeerror     at exports.loadRequestedDeps (/usr/share/npm/lib/install/deps.js:188:3)
45 error typeerror This is an error with npm itself. Please report this error at:
45 error typeerror     <http://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]
``` 

Is this maybe an issue with a bad deploy to NPM?  The fact that I'm only getting this with `fetch-mock` makes me think its package specific (that and that the current version tag is `beta`).

**Comment by danielBingham** [comment]
Never mind.  Version issue.  I was running npm version 3.5.2, which apparently is no longer compatible with many packages.  This is the version Ubuntu 18.04.1 has in the repos.

Manually upgraded to Node v13 and npm version 6.13.7 and it worked.
