### ISSUE TITLE
unable to restore mock between tests

### ISSUE THREAD

**Issue by elviswolcott** [wheresrhys/fetch-mock#533]
I tried `fetch-mock-jest`, but was unable to get it to work with ES import syntax, so I'm using plain `fetch-mock` with Jest as my test runner.

> Note: this code is TypeScript, but the issue is not related to typescript support.

Although this looks a bit odd, all it's doing is setting up an ES Module mock. AFAIK there's no issues related to this. The mix of `require()` and `import` is just for TypeScript (if you `import fetchMock from "node-fetch"` TypeScript uses the typings and ignores all of the mock related stuff).
```ts
jest.mock("node-fetch", () => {
  const nodeFetch = jest.requireActual("node-fetch");
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const mock = require("fetch-mock");
  const mocked = mock.sandbox();
  /*
  Object.assign(mocked.config, {
    fetch: nodeFetch,
  });
  */
  const { default: exclude, ...internals } = nodeFetch;
  return {
    default: mocked,
    __esModule: true,
    ...internals,
    ...mocked,
  };
});
// eslint-disable-next-line @typescript-eslint/no-var-requires
const fetchMock = require("node-fetch");
import { Request, Response } from "node-fetch";
```

Mocking:
(`no` returns a new response with the JSON body for a no response)
I've tried a bunch of combinations of `beforeEach`, `afterEach`, `restore`, `reset`, and `resetBehavior`, but haven't found anything that works. Obviously in this example you could just add the matcher once, but in my real use case sometimes I want to configure the endpoint's response in each test to be different.

```ts
beforeEach(() => {
  fetchMock.mock("https://yesno.wtf/api", no);
});

afterEach(() => {
  fetchMock.restore();
});
```

The error:

```bash
> package-name@0.0.0 test C:\Users\elvis\Desktop\fetch-mock-repro
> jest --config jestconfig.json --passWithNoTests

 FAIL  src/__tests__/index.test.ts
  YesNo SDK
    √ answers "yes" or "no" (10ms)
    × includes an image (16ms)

  ● YesNo SDK › includes an image

    fetch-mock: Adding route with same name or matcher as existing route. See `overwriteRoutes` option.

      44 | 
      45 | beforeEach(() => {
    > 46 |   fetchMock.mock("https://yesno.wtf/api", no);
         |             ^
      47 | });
      48 | 
      49 | afterEach(() => {

      at Object.<anonymous>.FetchMock.addRoute (node_modules/fetch-mock/cjs/lib/set-up-and-tear-down.js:37:9)
      at Object.<anonymous>.FetchMock.mock (node_modules/fetch-mock/cjs/lib/set-up-and-tear-down.js:7:8)
      at Object.<anonymous> (src/__tests__/index.test.ts:46:13)

  ● YesNo SDK › includes an image

    fetch-mock: No fallback response defined for GET to https://yesno.wtf/api

       6 |   forced: boolean;
       7 | }> => {
    >  8 |   const response = await fetch("https://yesno.wtf/api");
         |                               ^
       9 |   const json = await response.json();
      10 |   return json;
      11 | };

      at Function.Object.<anonymous>.FetchMock.executeRouter (node_modules/fetch-mock/cjs/lib/fetch-handler.js:167:9)
      at Function.Object.<anonymous>.FetchMock._fetchHandler (node_modules/fetch-mock/cjs/lib/fetch-handler.js:99:21)
      at Function.Object.<anonymous>.FetchMock.fetchHandler (node_modules/fetch-mock/cjs/lib/fetch-handler.js:90:14)
      at Object.proxy [as default] (node_modules/fetch-mock/cjs/lib/index.js:53:42)
      at src/index.ts:8:31
      at step (src/index.ts:33:23)
      at Object.next (src/index.ts:14:53)
      at src/index.ts:8:71
      at Object.<anonymous>.__awaiter (src/index.ts:4:12)
      at Object.yesno (src/index.ts:3:15)
      at src/__tests__/index.test.ts:59:26
      at step (src/__tests__/index.test.ts:44:23)
      at Object.next (src/__tests__/index.test.ts:25:53)
      at src/__tests__/index.test.ts:19:71
      at Object.<anonymous>.__awaiter (src/__tests__/index.test.ts:15:12)
      at Object.<anonymous> (src/__tests__/index.test.ts:58:27)

  console.warn node_modules/fetch-mock/cjs/lib/fetch-handler.js:156
    Unmatched GET to https://yesno.wtf/api

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        3.461s, estimated 4s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

I've put up a repo that reproduces the issue. It has some extra stuff (like travis config and eslint) that are part of the template I use, and can be ignored. Complete code [elviswolcott/fetch-mock-repro](https://github.com/elviswolcott/fetch-mock-repro).

**Comment by elviswolcott** [comment]
I managed to fix it (calling restore & reset beforeEach) and updated the linked repository with a working version in case any stumbles across this with the same issue.

**Comment by chet-manley** [comment]
Not entirely related, but there's a much easier way to mock with either `fetch-mock` or `fetch-mock-jest` and Jest. 
```javascript
// __mocks__/node-fetch.js
import fetchMock from 'fetch-mock-jest'

export default fetchMock.sandbox()
export { Headers, Request, Response } from 'node-fetch'
```

```javascript
// __tests__/your.test.js
import fetchMock, { Request, Response } from 'node-fetch'
...
```
I've also sent PR #532 which will allow you to avoid exporting `Headers`, `Request`, and `Response` from `node-fetch` when setting up your mock.
