### ISSUE TITLE
URI encoded query parameters are not matched

### ISSUE THREAD

**Issue by rvinzent** [wheresrhys/fetch-mock#554]
Hi, thanks for the package!

In the below code snippet I would expect at least one of the fetch mock endpoints to match successfully, but I am unable to make the match work. I have tried using the `query` match option as well as matching the full string URL, and the `URL` instance directly, but nothing seems to make my test pass. 

In the console output you can see that the logged actual URL and warnings for unmatched URL are identical. Is this a bug or am I missing something obvious?

[REPL](https://repl.it/repls/DimgreyUnrulyJavabytecode)

``` javascript
const { DateTime }  = require('luxon')
const fetch = require('isomorphic-fetch')
const fetchMock = require('fetch-mock')

const mockResponse = [{ id: 1, prop: 'value' }]
const datetime = DateTime.local()

const url = new URL('http://fake.com/api/any')
url.searchParams.append('date', datetime.toString())

fetchMock.getOnce(url, 200)
fetchMock.getOnce(url.toString(), 200)
fetchMock.getOnce('http://fake.com/api/any', {
  status: 200,
  query: { date: datetime.toString() }
})

fetch(url.toString()).then(response => {
  console.log(fetchMock.done())
})

setTimeout(() => { console.log('url: ', url.toString()) }, 1000)
```

Here is the console output from the REPL:
```
Warning: http://fake.com/api/any?date=2020-05-12T18%3A07%3A23.852-00%3A00 not called
Warning: http://fake.com/api/any?date=2020-05-12T18%3A07%3A23.852-00%3A00 not called
Warning: http://fake.com/api/any not called
false
url:  http://fake.com/api/any?date=2020-05-12T18%3A07%3A23.852-00%3A00
```

The logged URL and the URL displayed in the warning are identical.

----
EDIT: I am trying desperately to add a passing call in the REPL but it refuses to work. However, I see similar behavior in my project's tests when `fetch` is actually able to match successfully in other cases. Unfortunately I am unable to share the full code, and there is a bit more happenning under the hood, but the problem remains where we have both an "unmatched call" and a warning for an extra call on the same URL.

Here is the fetch mock setup, which I have also tried using the `query` match property: 
```javascript
    fetchMock.getOnce(`end:/api/any?dateParam=${expectedIsoString}`, {
      status: 200,
      body: JSON.stringify(mockResponse),
    })
```

Additionally, this test case passes fine, so I can be fairly sure this is a result of the query string encoding:

```javascript
    const mockResponse = [{ id: 1, prop: 'value' }]
    const expectedQueryString = '?param=value&arrayParam=firstValue&arrayParam=secondValue'
    fetchMock.getOnce(`end:/api/any${expectedQueryString}`, {
      status: 200,
      body: JSON.stringify(mockResponse),
    })
```
Here is the console:
```

    fetch-mock: No fallback response defined for GET to http://localhost/api/any?dateParam=2020-05-12T17%3A31%3A20.343Z

      143 |     }
      144 |     return authenticatedGet('/api/any', queryParams)
    > 145 |       .toPromise()
          |        ^
      146 |       .then(response => {
      147 |         expect(fetchMock.done()).toBeTruthy()
      148 |         expect(response).toStrictEqual(mockResponse)

      at Object.<anonymous>.FetchMock.executeRouter (node_modules/fetch-mock/cjs/lib/fetch-handler.js:167:9)
      at Object.<anonymous>.FetchMock._fetchHandler (node_modules/fetch-mock/cjs/lib/fetch-handler.js:99:21)
      at Object.<anonymous>.FetchMock.fetchHandler (node_modules/fetch-mock/cjs/lib/fetch-handler.js:90:14)
      at Observable._subscribe (node_modules/rxjs/src/internal/observable/dom/fetch.ts:93:5)
      at Observable.Object.<anonymous>.Observable._trySubscribe (node_modules/rxjs/src/internal/Observable.ts:238:19)
      at Observable.Object.<anonymous>.Observable.subscribe (node_modules/rxjs/src/internal/Observable.ts:219:14)
      at Object.subscribeToResult (node_modules/rxjs/src/internal/util/subscribeToResult.ts:34:19)
      at MergeMapSubscriber.Object.<anonymous>.MergeMapSubscriber._innerSub (node_modules/rxjs/src/internal/operators/mergeMap.ts:148:31)
      at MergeMapSubscriber.Object.<anonymous>.MergeMapSubscriber._tryNext (node_modules/rxjs/src/internal/operators/mergeMap.ts:141:10)
      at MergeMapSubscriber.Object.<anonymous>.MergeMapSubscriber._next (node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
      at MergeMapSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at TakeSubscriber.Object.<anonymous>.TakeSubscriber._next (node_modules/rxjs/src/internal/operators/take.ts:92:24)
      at TakeSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at FilterSubscriber.Object.<anonymous>.FilterSubscriber._next (node_modules/rxjs/src/internal/operators/filter.ts:101:24)
      at FilterSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at TapSubscriber.Object.<anonymous>.TapSubscriber._next (node_modules/rxjs/src/internal/operators/tap.ts:125:22)
      at TapSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:99:12)
      at BehaviorSubject.Object.<anonymous>.BehaviorSubject._subscribe (node_modules/rxjs/src/internal/BehaviorSubject.ts:27:18)
      at BehaviorSubject.Object.<anonymous>.Observable._trySubscribe (node_modules/rxjs/src/internal/Observable.ts:238:19)
      at BehaviorSubject.Object.<anonymous>.Subject._trySubscribe (node_modules/rxjs/src/internal/Subject.ts:116:33)
      at BehaviorSubject.Object.<anonymous>.Observable.subscribe (node_modules/rxjs/src/internal/Observable.ts:219:14)
      at Observable.Object.<anonymous>.Observable._subscribe (node_modules/rxjs/src/internal/Observable.ts:282:29)
      at Observable.Object.<anonymous>.Observable.subscribe (node_modules/rxjs/src/internal/Observable.ts:218:14)
      at DoOperator.Object.<anonymous>.DoOperator.call (node_modules/rxjs/src/internal/operators/tap.ts:81:19)
      at Observable.Object.<anonymous>.Observable.subscribe (node_modules/rxjs/src/internal/Observable.ts:214:25)
      at FilterOperator.Object.<anonymous>.FilterOperator.call (node_modules/rxjs/src/internal/operators/filter.ts:71:19)
      at Observable.Object.<anonymous>.Observable.subscribe (node_modules/rxjs/src/internal/Observable.ts:214:25)
      at TakeOperator.Object.<anonymous>.TakeOperator.call (node_modules/rxjs/src/internal/operators/take.ts:72:19)
      at Observable.Object.<anonymous>.Observable.subscribe (node_modules/rxjs/src/internal/Observable.ts:214:25)
      at MergeMapOperator.Object.<anonymous>.MergeMapOperator.call (node_modules/rxjs/src/internal/operators/mergeMap.ts:100:19)
      at Observable.Object.<anonymous>.Observable.subscribe (node_modules/rxjs/src/internal/Observable.ts:214:25)
      at MergeMapOperator.Object.<anonymous>.MergeMapOperator.call (node_modules/rxjs/src/internal/operators/mergeMap.ts:100:19)
      at Observable.Object.<anonymous>.Observable.subscribe (node_modules/rxjs/src/internal/Observable.ts:214:25)
      at node_modules/rxjs/src/internal/Observable.ts:360:12
      at Observable.Object.<anonymous>.Observable.toPromise (node_modules/rxjs/src/internal/Observable.ts:358:12)
      at Object.<anonymous> (src/services/__tests__/http.test.ts:145:8)

  ● authenticated fetch methods › authenticatedGet serializes datetimes in ISO format

    expect.assertions(2)

    Expected two assertions to be called but received zero assertion calls.

      138 |     })
      139 | 
    > 140 |     expect.assertions(2)
          |            ^
      141 |     const queryParams: UrlQueryParams = {
      142 |       dateParam: datetime,
      143 |     }

      at Object.<anonymous> (src/services/__tests__/http.test.ts:140:12)

  console.warn node_modules/fetch-mock/cjs/lib/fetch-handler.js:156
    Unmatched GET to http://localhost/api/any?dateParam=2020-05-12T17%3A31%3A20.343Z
```

The notable lines are
```
fetch-mock: No fallback response defined for GET to http://localhost/api/any?dateParam=2020-05-12T17%3A31%3A20.343Z
```
 and
```
 console.warn node_modules/fetch-mock/cjs/lib/fetch-handler.js:156
    Unmatched GET to http://localhost/api/any?dateParam=2020-05-12T17%3A31%3A20.343Z
```

As you can see they are identical URLs.

**Comment by wheresrhys** [comment]
Could you try with 9.9.0 - not specifically designed to fix this issue, but might help

**Comment by wheresrhys** [comment]
I think the main problem is that fetch is not actually getting mocked. 

In your example if instead of

```js
const fetch = require('isomorphic-fetch')
```

You do

```
require('isomorphic-fetch')
```
... which adds `fetch` as a global you can reference without declaring as a local variable, then fetchMock will be able to mock it successfully. 

More details here http://www.wheresrhys.co.uk/fetch-mock/#usageglobal-non-global - let me know if it could be clearer

**Comment by rvinzent** [comment]
Hi thanks for the quick response. Upgrading the version ended up fixing the issue.

I had already been playing around with the REPL, using different fetch implementations in both global and local scope and it never ended up working out. Oh well...

Thanks!

**Comment by rvinzent** [comment]
I stopped trying to match the actual URL and just use the `query` match instead

**Comment by rvinzent** [comment]
> I stopped trying to match the actual URL and just use the query match instead

...which upon further debugging does not match ISO date strings.

I am now using `qs` for query param stringification and the `query` match option for `fetchMock`. It still produces the following messages with the config:
```
    fetchMock.getOnce(
      'begin:/api/any',
      {
        status: 200,
        body: mockResponse,
      },
      {
        query: expectedQueryParams,
      },
    )
...
    fetch-mock: No fallback response defined for GET to /api/any?param=value&arrayParam=firstValue&arrayParam=secondValue&dateParam=2020-05-14T00%3A52%3A54.901Z
...
/api/any?param=value&arrayParam=firstValue&arrayParam
=secondValue&dateParam=2020-05-14T00%3A52%3A54.901Z
```
