### ISSUE TITLE
`Right-hand side of 'instanceof' is not an object` with jsdom

### ISSUE THREAD

**Issue by jdelStrother** [wheresrhys/fetch-mock#884]
Thanks for fetch-mock!

I've been trying to upgrade fetch-mock-jest -> @fetch-mock/jest, but had some issues with our tests that use jsdom, where Request/Response etc aren't defined on globalThis. I suspect it's the same issue as https://github.com/wheresrhys/fetch-mock/issues/864

I created an example repo at https://github.com/jdelStrother/fetch-mock-jest

```shellsession
$ npm test

> jest-fetch-mock@1.0.0 test
> jest --all

 PASS  ./mock-old.test.js
 FAIL  ./mock.test.js
  ● can fetch stuff

    TypeError: Right-hand side of 'instanceof' is not an object

       8 |
       9 | it("can fetch stuff", async () => {
    > 10 |   let r = await fetch("http://example.com");
         |                 ^
      11 |   expect(r.status).toEqual(418);
      12 | });
      13 |

      at FetchMockJest._callee$ (node_modules/fetch-mock/dist/esm/FetchMock.js:56:25)
      at fetch (mock.test.js:10:17)
      at call (mock.test.js:2:1)
      at Generator.tryCatch (mock.test.js:2:1)
      at Generator._invoke [as next] (mock.test.js:2:1)
      at asyncGeneratorStep (mock.test.js:2:1)
      at asyncGeneratorStep (mock.test.js:2:1)
      at _next (mock.test.js:2:1)
      at Object.<anonymous> (mock.test.js:2:1)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        1.178 s
Ran all test suites.
```

The first error comes from https://github.com/wheresrhys/fetch-mock/blob/d1ccb8a1f57b694a123cb3b8e6a6b81f752f7b0a/packages/fetch-mock/src/FetchMock.ts#L97 , but if I naively bypass that check there seem to be a rabbithole of further errors (`Response is not defined`, `ReadableStream is not defined` ...)

I'm not sure if jsdom is something you want to support, but thought it was worth highlighting as something that used to work under fetch-mock-jest

**Comment by jdelStrother** [comment]
> there seem to be a rabbithole of further errors

actually, maybe the rabbithole isn't that deep. If I use this custom jest environment:

```
import { TestEnvironment } from "jest-environment-jsdom";

export default class CustomTestEnvironment extends TestEnvironment {
  async setup() {
    await super.setup();

    this.global.Request = Request;
    this.global.Response = Response;
    this.global.ReadableStream = ReadableStream;

  }
}
```

that seems sufficient to get fetch-mock working again

**Comment by wheresrhys** [comment]
Thanks for investigating this and sharing your workaround. 

I'll leave this issue open for others to find for now. This is something I should either add to the docs or find a way to build the workaround into the library, but I won't have time to look into it for the next few weeks at least
